export enum userRole {
  JSB_GS = 1,
  JSB_FBZ = 2,
  JSB_BZ = 3,
  XMB_BZ = 4,
  XMB_FBZ = 5,
  XMB_GS = 6,
  SFB_GS = 7,
  SFB_FBZ = 8,
  SFB_BZ = 9,
  ZXB_BZ = 10,
  ZXB_FBZ = 11,
  ZXB_GS = 12,
  MSC_GS = 13,
  MSC_FMS = 14,
  MSC_MSZ = 15,
  LSH_HZ = 16,
  LSH_JSFHZ = 17,
  LSH_CWFHZ = 18,
  LSH_ZGFZR = 19,
  member = 20,
}
export enum cadresRole {
  JSB_FBZ = 2,
  JSB_BZ = 3,
  XMB_BZ = 4,
  XMB_FBZ = 5,
  SFB_FBZ = 8,
  SFB_BZ = 9,
  ZXB_BZ = 10,
  ZXB_FBZ = 11,
  MSC_FMS = 14,
  MSC_MSZ = 15,
  LSH_HZ = 16,
  LSH_JSFHZ = 17,
  LSH_CWFHZ = 18,
}


export const userAdminRole = [
  userRole.LSH_CWFHZ,
  userRole.LSH_HZ,
  userRole.LSH_JSFHZ,
  userRole.LSH_ZGFZR,
  userRole.MSC_FMS,
  userRole.MSC_MSZ,
  userRole.SFB_BZ,
  userRole.SFB_FBZ,
  userRole.XMB_BZ,
  userRole.XMB_FBZ,
  userRole.ZXB_BZ,
  userRole.ZXB_FBZ,
  userRole.JSB_BZ,
  userRole.JSB_FBZ,
]
